
#[DHCPOPTION0]
Enable=1
Tag=43
Value=
#[DHCPOPTION1]
Enable=1
Tag=60
Value=HSI_PSG1282N
#[DHCPOPTION2]
Enable=0
Tag=60
Value=
#[DHCPOPTION3]
Enable=0
Tag=60
Value=
#[DHCPOPTION4]
Enable=0
Tag=60
Value=
